[package]
name = "eip712_nft_minter"
version = "0.1.0"
edition = "2021"

[dependencies]
ethereum-types = "0.14.1"
lazy_static = "1.4.0"
regex = "1.10.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
validator = { version = "0.18.1", features = ["derive"] }